server:
  port: 20030

spring:
  profiles:
    active: dev
      
  application:
    name: webflux
  
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

management:
  endpoints:
    web:
      exposure:
        include: "*"